// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uemkpndmtlduqnlakwnk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbWtwbmRtdGxkdXFubGFrd25rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNDA0NTcsImV4cCI6MjA2NDgxNjQ1N30.R5zmftnXVwzpa-0KBkM4MRyMN54p89YD4bTMGf7sBmg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);